# Use an official Node runtime as a parent image
FROM node:16-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the frontend package.json and package-lock.json into the container
COPY package*.json ./

# Install frontend dependencies
RUN npm install

# Copy the rest of the frontend code into the container
COPY . .

# Expose the port where your React app will run
EXPOSE 5000

# Command to start the React development server
CMD ["npm", "run", "dev"]
