version: '3.8'

services:
  frontend:
    build:
      context: ./frontend                
      dockerfile: Dockerfile.frontend   
    ports:
      - "3000:5000"                     
    depends_on:
      - backend                       

  backend:
    build:
      context: ./backend                
      dockerfile: Dockerfile.backend    
    ports:
      - "5000:5000"                    
    environment:
      - FLASK_ENV=development         
